# Generated by Django 4.0.6 on 2022-07-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supertype',
            old_name='hero',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='supertype',
            name='villain',
        ),
    ]
