# Generated by Django 4.0.6 on 2022-07-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
        ('super_types', '0002_rename_hero_supertype_type_remove_supertype_villain'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertype',
            name='super_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supers.super'),
        ),
    ]
